#!/usr/bin/env python3
"""Generate ``trotter_step.ll``: symmetric Trotter steps of a spin chain.

Second-order (symmetric) Trotterization applies the Hamiltonian terms forwards
and then backwards, so the last term of one step and the first term of the next
are the *same* term.  Their CNOT ladders cancel and their Rz rotations fuse --
the classic reason a Trotter circuit is worth running an optimizer over.

    python examples/gen_trotter.py > examples/trotter_step.ll
"""

from __future__ import annotations

NUM_QUBITS = 4
J = 0.35  # ZZ coupling
HZ = 0.20  # longitudinal field
HX = 0.15  # transverse field
DT = 0.1
NUM_STEPS = 4


def qubit(i: int) -> str:
    return "null" if i == 0 else f"inttoptr (i64 {i} to %Qubit*)"


def result(i: int) -> str:
    return "null" if i == 0 else f"inttoptr (i64 {i} to %Result*)"


def gate(name: str, *args: str) -> str:
    return f"  call void @__quantum__qis__{name}__body({', '.join(args)})"


def rz(theta: float, i: int) -> str:
    return gate("rz", f"double {theta:.17g}", f"%Qubit* {qubit(i)}")


def zz_term(i: int, j: int, theta: float) -> list[str]:
    return [
        gate("cnot", f"%Qubit* {qubit(i)}", f"%Qubit* {qubit(j)}"),
        rz(theta, j),
        gate("cnot", f"%Qubit* {qubit(i)}", f"%Qubit* {qubit(j)}"),
    ]


def x_term(i: int, theta: float) -> list[str]:
    return [
        gate("h", f"%Qubit* {qubit(i)}"),
        rz(theta, i),
        gate("h", f"%Qubit* {qubit(i)}"),
    ]


def step(reverse: bool) -> list[str]:
    """One Trotter step; ``reverse`` emits the whole term list backwards.

    Alternating forward and reversed steps is second-order (symmetric)
    Trotterization: the term at a step boundary is applied twice in a row, so
    its CNOT ladder cancels and its rotation fuses.
    """
    pairs = [(i, i + 1) for i in range(NUM_QUBITS - 1)]
    singles = list(range(NUM_QUBITS))
    terms: list[list[str]] = []
    for i, j in pairs:
        terms.append(zz_term(i, j, 2 * J * DT))
    for i in singles:
        terms.append([rz(2 * HZ * DT, i)])
    for i in singles:
        terms.append(x_term(i, 2 * HX * DT))
    if reverse:
        terms.reverse()
    return [line for term in terms for line in term]


def main() -> str:
    body: list[str] = []
    for index in range(NUM_STEPS):
        order = "reversed" if index % 2 else "forward"
        body.append(f"  ; --- Trotter step {index + 1} ({order} term order) ---")
        body += step(reverse=bool(index % 2))
    body.append("  ; --- measure out ---")
    for i in range(NUM_QUBITS):
        body.append(
            f"  call void @__quantum__qis__mz__body("
            f"%Qubit* {qubit(i)}, %Result* {result(i)})"
        )

    declares = "\n\n".join(
        [
            "declare void @__quantum__qis__h__body(%Qubit*)",
            "declare void @__quantum__qis__rz__body(double, %Qubit*)",
            "declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)",
            "declare void @__quantum__qis__mz__body(%Qubit*, %Result*) #1",
        ]
    )
    return f"""; {NUM_STEPS} symmetric Trotter steps of a 4-spin transverse-field Ising chain.
; Generated by examples/gen_trotter.py (J={J}, hz={HZ}, hx={HX}, dt={DT}).
; ModuleID = 'trotter_step'
source_filename = "trotter_step"

%Qubit = type opaque
%Result = type opaque

define void @main() #0 {{
entry:
{chr(10).join(body)}
  ret void
}}

{declares}

attributes #0 = {{ "entry_point" "qir_profiles"="base_profile" \
"required_num_qubits"="{NUM_QUBITS}" "required_num_results"="{NUM_QUBITS}" }}
attributes #1 = {{ "irreversible" }}

!llvm.module.flags = !{{!0, !1}}

!0 = !{{i32 1, !"qir_major_version", i32 1}}
!1 = !{{i32 7, !"qir_minor_version", i32 0}}
"""


if __name__ == "__main__":
    print(main(), end="")
